### ISSUE TITLE
Fix broken unit tests for VoidFinder classes

### ISSUE THREAD

**Issue by sybenzvi** [DESI-UR/VAST#65] opened 2022-02-09 21:38 UTC
The `test_VF.py` module does not work with pytest, which seems to have trouble finding the cythonized VoidFinder submodules.

**Comment by sybenzvi** [comment] 2022-02-09 21:41
Running the unit tests through [pytest-runner](https://stackoverflow.com/questions/48330471/running-pytest-with-cython-how-to-compile-cython-modules-in-pytest) seems to fix the problem of importing cythonized modules, but now the test results are inconsistent between python 3.7 (succeeds) and 3.8 and 3.9 (fails).

**Comment by sybenzvi** [comment] 2022-02-09 21:50
Specifically, the [verification of the number of maximal spheres](https://github.com/DESI-UR/VAST/blob/1e37f9ae2007f18ac4d742fe56ea7eab0637b53b/python/vast/test/test_VF.py#L169) matches the truth file in Python 3.7 but not 3.8 & 3.9. Unfortunately, I am not reproducing this in a Python 3.9 environment on my computer.

**Comment by QuiteAFoxtrot** [comment] 2022-03-12 20:31
I also cannot reproduce from a clean Python 3.8 venv on my Ubuntu 20.04.2 LTS :(

**Comment by QuiteAFoxtrot** [comment] 2022-03-12 20:33
also maybe for fixing the pytest running without pytest-runner, which seems maybe to be deprecated?  slap a 'python setup.py build_ext --inplace' to get the cython to build before running the 'pytest' command?  If thats helpful

**Comment by kadglass** [comment] 2022-10-12 15:13
Fixed with PR #91 .  The issue was two-fold: slight differences due to number precision errors, which then caused the order of the holes to be different in the files.  This was fixed by comparing the values using `np.isclose()` after sorting the tables by each of the columns (void flag, radius, x, y, z).

**Closed by kadglass** 2022-10-12 15:13 UTC
